num1 =float(input("Notas do 1°bimestre:"))
num2 =float(input("Notas do 2°bimestre:"))
num3 =float(input("Notas do 3°bimestre:"))
num4 =float(input("Notas do 4°bimestre:"))
print("A sua média foi:", (num1+num2+num3+num4)/3)
